### ISSUE TITLE
"CUDA error: invalid configuration argument" when increasing the batch size

### ISSUE THREAD

**Issue by alexx-km** [swc-17/SparseDrive#62]
Hello,
we currently have some issues deploying the training on our cluster with an increased batch size. It seems to run fine with a batch size of 8, but when we try to start the training process with 12 or 16, we get the following error:

```console
Exception has occurred: RuntimeError
CUDA error: invalid configuration argument
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
  File "/project_workspace/SparseDrive/projects/mmdet3d_plugin/models/blocks.py", line 171, in forward
    output = torch.cat([output, instance_feature], dim=-1)
```

![Code_TQZqL7Hw02](https://github.com/user-attachments/assets/174ae520-7c9e-4d51-89a1-efaf08c59210)

The current deployment/setup and training process is as follows:
1. Create a Docker Image with the repo's requirements (CUDA, Python, torch etc.) in a conda (base) environment on a Virtual Machine (Linux, use TORCH_CUDA_ARCH_LIST to build torch for the A100 on the cluster) 
2. Start container on Cluster with the docker image 
3. Build the deformable_aggregation kernel on the Cluster with pip install -e . (seems to work, deformable_aggregation_ext is listed in pip packages with the location pointing towards the opt folder)
4. Start the training process with one GPU (A100 40GB)

Maybe relevant information:
- We do not have write access on the cluster to the Python packages, therefore, the package is installed in the user directory
- When I try to execute the code that results in the exception in the debug console, the command works without any issues
- The operation that results in the crash runs fine the first few iterations before it finally crashes
- The training runs fine with bs=8, using ~24GB of VRAM --> increasing to 12 should be feasible on a GPU with 40GB of VRAM
- Adding "CUDA_LAUNCH_BLOCKING=1" to the environment variables just leads to this hint diesappearing and no additional information

**Comment by swc-17** [comment]
Hi, are you using same GPUs with batch_size 8 and 16? I think the problem may be related to the compilation of deformable aggregation.

**Comment by alexx-km** [comment]
Yes, I tested 8, 12 and 16 on the same GPU. Only 8 worked without the described issue. But shouldn't all versions have the same problems when there is a problem with the compilation of the deformable aggregation?

**Comment by alexx-km** [comment]
I just tested it on a different setup, where I'm sure that the kernel is compiled correctly. Here, a batch size <= 8 works (tested it e.g. with 6). It was also possible to increase the batch size to 11. Any value larger than that results in the crash, although 5GB of VRAM are free and one sample leads to an increase of ~1GB.

**Comment by swc-17** [comment]
Hi, I discussed this problem with the author of Sparse4D, the answer is that it should be related to the cuda op, the cuda op from Sparse4Dv3 encounters this problem with large batch size sometimes, so you may need to adapt to cuda op in Sparse4Dv2 repo.

**Comment by alexx-km** [comment]
Thank you for your reply, I think we solved the issue today.

Apparently, it is caused by an integer overflow [here](https://github.com/swc-17/SparseDrive/blob/ddb706bad6ce0b349d3d64bafddf538c8bad38e0/projects/mmdet3d_plugin/ops/src/deformable_aggregation_cuda.cu#L281). It can be fixed by changing the datatype of batch_size and num_kernels to long int. Additionally, I almost certain that the [idx ](https://github.com/swc-17/SparseDrive/blob/ddb706bad6ce0b349d3d64bafddf538c8bad38e0/projects/mmdet3d_plugin/ops/src/deformable_aggregation_cuda.cu#L146) should also be a long int. With these changes, we can now train with higher batch_sizes.

**Comment by swc-17** [comment]
Good point! We will update this in the code later.

**Comment by qwert1887** [comment]
@alexx-km Hi, could you please share more details about modifying the file you mentioned? I look forward to your reply!

> Thank you for your reply, I think we solved the issue today.
> 
> Apparently, it is caused by an integer overflow [here](https://github.com/swc-17/SparseDrive/blob/ddb706bad6ce0b349d3d64bafddf538c8bad38e0/projects/mmdet3d_plugin/ops/src/deformable_aggregation_cuda.cu#L281). It can be fixed by changing the datatype of batch_size and num_kernels to long int. Additionally, I almost certain that the [idx ](https://github.com/swc-17/SparseDrive/blob/ddb706bad6ce0b349d3d64bafddf538c8bad38e0/projects/mmdet3d_plugin/ops/src/deformable_aggregation_cuda.cu#L146) should also be a long int. With these changes, we can now train with higher batch_sizes.

**Comment by qwert1887** [comment]
It works! Thanks for your work.

**Comment by alexx-km** [comment]
@qwert1887 Sorry for the late reply. I think we changed num_kernels, batch_size and idx to long int. After that it worked without issues. But I'm glad that it already worked out for you!
